---
apiVersion: v1
kind: Service
metadata:
  name: 3camwood
  labels:
    app: 3camwood
spec:
  type: NodePort
  ports:
  - port: 80
    protocol: TCP
    name: http
  selector:
    app: 3camwood
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: 3camwood
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: 3camwood
    spec:
      containers:
      - name: 3camwood
        image: 3camwood
        imagePullPolicy: Never
        ports:
        - containerPort: 80
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: 3camwood-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
    ingress.kubernetes.io/ssl-redirect: "false"
    kubernetes.io/tls-acme: 'true'
spec:
  tls:
  - hosts:
      - 3camwood.qchsag.ca
    secretName: 3camwood.qchsag.ca
  rules:
  - http:
      paths:
      - path: /
        backend:
          serviceName: 3camwood
          servicePort: 80
    host: 3camwood.qchsag.ca
